name: backup-password

on:
  workflow_dispatch: 

jobs:
  backup-password:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your preferred version
          cache: 'pip'   
          
      - name: Install dependencies
        run: pip install gdown

      - name: Grab password
        run: gdown 1-zNzjqc1j21o1KiI1qEjbtADMaTq77Mr

      - name: Save to Repo
        run: |
          # Configure Git Bot credentials
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Stage the specific file
          git add passwords.kdbx
          
          # Commit and push only if the file actually changed
          if git diff --cached --quiet; then
            echo "No changes detected in the downloaded file."
          else
            git commit -m "chore: auto-update file via curl"
            git push origin main
          fi
